### PR TITLE
Send message refactor

### LINKED ISSUE #1184: [Airbrake] [Production] can't convert Hash into Float
**Airbrake error:** [#0627](https://herokuapp50070218herokucom.airbrake.io/projects/123672/groups/1989192819728810627)
**Airbrake project:** just-match-api-eu

**Error type:** `TypeError`
**Error message:** `` can't convert Hash into Float ``
**Where:** `users#batch_action`
**Occurred at:** Jul 07, 2017 14:46:57 UTC
**First seen at:** Jul 07, 2017 13:31:02 UTC
**Occurrences:** 3 ( since last deploy on `<no information>`)
**Severity:** `error`

**URL:** [http://admin.justarrived.se/users/batch_action?q%5Buser_tags_tag_id_eq%5D=103](http://admin.justarrived.se/users/batch_action?q%5Buser_tags_tag_id_eq%5D=103)
**File:** `[PROJECT_ROOT]/app/support/message_user.rb`

**Backtrace:**
```
[PROJECT_ROOT]/app/support/message_user.rb:23:in %
[PROJECT_ROOT]/app/support/message_user.rb:23:in call
[PROJECT_ROOT]/app/support/message_user.rb:5:in call
[PROJECT_ROOT]/app/support/message_users.rb:20:in block (2 levels) in call
```

### PR DESCRIPTION
**Pull request by buren**
Closes #1184

### CODE REVIEW

File: app/services/send_admin_message.rb [hunk 1]
```diff
@@ -2,7 +2,7 @@
 
 class SendAdminMessage
   def self.call(users:, type:, subject:, template:, language_id:, support_user: User.main_support_user) # rubocop:disable Metrics/LineLength
-    response = MessageUsers.call(
+    response = MessageUsersService.call(
```
Comment (burenbot) [inline app/services/send_admin_message.rb]: Similar code found in 1 other location (mass = 30) ([app/services/send\_admin\_message.rb#5](https://github.com/justarrived/just_match_api/blob/90603c1279fbe504cd29d5a4c39c56f1624c2309/app/services/send_admin_message.rb#L5-L12) and [app/services/send\_admin\_communication\_template.rb#13](https://github.com/justarrived/just_match_api/blob/90603c1279fbe504cd29d5a4c39c56f1624c2309/app/services/send_admin_communication_template.rb#L13-L20))

File: app/services/send_admin_communication_template.rb [hunk 2]
```diff
@@ -10,7 +10,7 @@ def self.call(users:, job:, communcation_template:, type:, support_user: User.ma
       data[:job_description] = job.description
     end
 
-    response = MessageUsersFromTemplate.call(
+    response = MessageUsersFromTemplateService.call(
```
Comment (burenbot) [inline app/services/send_admin_communication_template.rb]: Similar code found in 1 other location (mass = 30) ([app/services/send\_admin\_communication\_template.rb#13](https://github.com/justarrived/just_match_api/blob/90603c1279fbe504cd29d5a4c39c56f1624c2309/app/services/send_admin_communication_template.rb#L13-L20) and [app/services/send\_admin\_message.rb#5](https://github.com/justarrived/just_match_api/blob/90603c1279fbe504cd29d5a4c39c56f1624c2309/app/services/send_admin_message.rb#L5-L12))

File: app/notifiers/deliver_notification.rb [hunk 3]
```diff
@@ -3,7 +3,7 @@
 class DeliverNotification
   def self.call(envelope, locale)
     envelope.deliver_later
-  rescue Redis::ConnectionError => e
+  rescue Redis::ConnectionError, Redis::CannotConnectError => e
```
Comment (burenbot) [inline app/notifiers/deliver_notification.rb]: DeliverNotification#self.call has the variable name 'e'

[Read more about it here.](https://github.com/troessner/reek/blob/master/docs/Uncommunicative-Variable-Name.md)

File: app/services/message_users_service.rb [hunk 4]
```diff
@@ -1,6 +1,6 @@
 # frozen_string_literal: true
 
-class MessageUsers
+class MessageUsersService
```
Comment (burenbot) [inline app/services/message_users_service.rb]: MessageUsersService has at least 6 instance variables

[Read more about it here.](https://github.com/troessner/reek/blob/master/docs/Too-Many-Instance-Variables.md)

File: app/services/message_users_from_template_service.rb [hunk 5]
```diff
@@ -1,6 +1,6 @@
 # frozen_string_literal: true
 
-class MessageUsersFromTemplate
+class MessageUsersFromTemplateService
```
Comment (burenbot) [inline app/services/message_users_from_template_service.rb]: MessageUsersFromTemplateService has at least 5 instance variables

[Read more about it here.](https://github.com/troessner/reek/blob/master/docs/Too-Many-Instance-Variables.md)

File: app/services/message_user_service.rb [hunk 6]
```diff
@@ -0,0 +1,65 @@
...
+    @user = user
+    @template = template
+    @subject = subject
+
+    attributes = @user.attributes.
+                 transform_keys { |key| "user_#{key}" }.
+                 merge!(@data)
+
+    @service = SendMessageService.new(body: template, subject: subject, data: attributes)
+  rescue KeyError => e
```
Comment (burenbot) [inline app/services/message_user_service.rb]: MessageUserService#initialize has the variable name 'e'

[Read more about it here.](https://github.com/troessner/reek/blob/master/docs/Uncommunicative-Variable-Name.md)

File: app/services/message_user_service.rb [hunk 7]
```diff
@@ -0,0 +1,65 @@
+# frozen_string_literal: true
+
+class MessageUserService
```
Comment (burenbot) [inline app/services/message_user_service.rb]: MessageUserService has at least 8 instance variables

[Read more about it here.](https://github.com/troessner/reek/blob/master/docs/Too-Many-Instance-Variables.md)
